version: '3.8'

services:
  app:
    image : rishabhm148/rishabhlabs1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/LearningRnD
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      DATABASE_HOST: docker_mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: LearningRnD


